[env]
# NOTE: While these configurations fit on a 2MB card, it is not tested!
# Success with 79.5% (but NO OTA!)
board_build.partitions = bare_minimum_2MB.csv
board_upload.flash_size = 2MB
board_upload.maximum_size = 2097152