; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-c6-dev
extra_configs = 
	platformio-local.ini
	platformio-16MB.ini

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
test_framework = googletest
monitor_speed = 115200
monitor_filters = 
	default
	esp32_exception_decoder
lib_deps = 
	tzapu/WiFiManager@^2.0.17
	dawidchyrzynski/home-assistant-integration@^2.1.0
	arduino-libraries/NTPClient@^3.2.1
	jchristensen/Timezone@^1.2.5
	google/googletest@^1.15.2
	fastled/FastLED@^3.10.2
build_flags = -DFEATURE_ARDUINO_OTA=1
check_tool = cppcheck
check_skip_packages = yes
check_severity = high, medium, low
check_flags = 
	cppcheck: --enable=warning
	cppcheck: --inline-suppr

[env:esp32-c6-dev]
build_type = debug

[env:esp32-c6-ota]
build_type = release
upload_protocol = espota
