[env]
# NOTE: While these configurations fit on a 4MB card, it is not tested!
# Success with 39.7% (but NO OTA!)
#board_build.partitions = storage_4MB_noota.csv
# Success with 53.0%
board_build.partitions = huge_app.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

# This one fails
# The program size (1666816 bytes) is greater than maximum allowed (1310720 bytes)
# board_build.partitions = default.csv
